version: '3'
services:
  app:
    build: ./app
    restart: always
    ports:
      - '8080:8080'
    env-file:
      - ./.env
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - '3306:3306'
    env-file:
      - ./.env
