version: '3'
services:
  app:
    build: ./app
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - ./app/.env
    links:
      - db
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    env_file:
      - ./db/.env
