version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB=mapa_pressao-01
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_PORT=3360
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - '3360:3360'
    environment:
      - MYSQL_DATABASE=mapa_pressao-01
      - MYSQL_ROOT_PASSWORD=123456
